<?php

namespace Emarref\Bundle\TwigDoctrineLoaderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends EntityRepository implements TemplateRepositoryInterface
{
    /**
     * {@inheritdoc}
     */
    public function getTemplateByName($name)
	{
        $query_builder = $this->createQueryBuilder('t');

        $query = $query_builder
            ->select('t')
            ->where('t.name = :identifier')->setParameter('identifier', $name)
            ->getQuery();

        return $query->getSingleResult();
	}
}
